In [1]:
import numpy as np
from functional import convolution as cv
x = np.asarray([[1,2,0,1], [1, 0 , 1, 1], [1, 2, 0, 0], [0, 2, 1, 0]])
w = np.asarray([[1, 0], [1, 1]])
o = cv.conv_3_3(x, w)

In [2]:
o

array([[2., 3., 2.],
       [4., 2., 1.],
       [3., 5., 1.]])

In [27]:
x.shape, w.shape

((5, 5), (3, 3))

In [3]:
x = np.expand_dims(x, axis=[0, 1])
w = np.expand_dims(w, axis=[0, 1])
o = np.expand_dims(o, axis=[0, 1])

In [7]:
dL = np.asarray([[1, 1, 0], [0, 0, 1], [1, 0, 0]]).reshape(1, 1, 3, 3) 
dx, dw = cv.conv_grad(x, w, dL=dL)
dx, dw = dx.squeeze(), dw.squeeze()

In [8]:
dx, dw

(array([[1., 1., 0., 0.],
        [1., 2., 2., 0.],
        [1., 0., 1., 1.],
        [1., 1., 0., 0.]], dtype=float32),
 array([[5., 5.],
        [1., 3.]], dtype=float32))